### ISSUE TITLE
Support managed tenant URLs

### ISSUE THREAD

**Issue by kejoat** [dynatrace-oss/dynatrace-aws-s3-log-forwarder#45]
Hi,

coming from the recent blog article (https://www.dynatrace.com/news/blog/accelerate-your-cloud-journey-with-dynatrace-observability-for-aws-s3-logs/) and reading "or Log Monitoring Classic" I assumed the forwarder can also be used for managed DT instances.

But reading the _dynatrace.py_ it seems only API URIs from SaaS live instances are supported.
A Managed instance would produce a POST API string like "_companydomain/api/v2/logs/ingest_" which would obviously not work I guess.

Adding this as Feature request as I am not sure if that was in the scope of the forwarder, but I think adding support for Environment ActiveGate URIs would not be a lot of work.

Best regards,
Johannes

**Comment by azimnicki** [comment]
Hey kejoat,

Thanks for reaching out to us. We plan to extend documentation and the forwarder to enable its use with Logs Classic on managed clusters. We're actively working on it now.

From a network connectivity perspective, as Environment Active Gates are normally not internet-facing, we will enable optional configuration for the log forwarding AWS Lambda function to run on a VPC you define from which the Environment Active Gate must be reachable. 

If you'd like to describe your use case in more detail, please let us know.
